# This is a basic workflow to help you get started with Actions

name: K3D

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install k3d
        run: curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
        
      - name: K3D cluster create
        run: k3d create cluster
